# Generated by Django 5.0.6 on 2024-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_email_verified',
            field=models.TextField(default=False),
        ),
    ]
